# To enable logging, use the snippet per the documentation.
# Delaying log output may help catch issues close to startup. Uncomment and adjust if necessary (default is 1000ms)
#CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000

# Uncomment both to enable encoder(s)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# nice_custom - Custom display configuration
# Modify these values according to your display

CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_DISPLAY=y
# In case the user decides to use an OLED screen, this would be better to keep it disabled
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# Enable nice_custom, disable others
CONFIG_NICE_CUSTOM_ON=y
CONFIG_NICE_OLED_ON=n
CONFIG_NICE_EPAPER_ON=n

# TODO: dongle / central as single display mode
CONFIG_NICE_OLED_WIDGET_CENTRAL_SHOW_BATTERY_PERIPHERAL_ALL=n
CONFIG_NICE_OLED_WIDGET_CENTRAL_SHOW_BATTERY_PERIPHERAL_ONLY=y
CONFIG_NICE_OLED_WIDGET_CENTRAL_SHOW_BATTERY_PERIPHERAL_AND_CENTRAL=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_LV_Z_MEM_POOL_SIZE=8192
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
